# Generated by Django 2.1.7 on 2022-10-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
    ]
