# Generated by Django 4.1.2 on 2022-10-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vblog', '0003_post_created_on_post_image_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='pic'),
        ),
    ]
